# Generated by Django 3.2.6 on 2021-08-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(max_length=7),
        ),
    ]
